name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["*"]

jobs:
  build-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
  build-2:
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v3
        -   name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
        -   name: Build with Maven
            run: xvfb-run mvn clean install
