name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run mvn clean install
      - name: Build with Maven Windows
        if: matrix.os == 'windows-latest'
        run:  mvn clean install
      - name: Build with Maven MacOS
        if: matrix.os == 'macos-latest'
        run: mvn clean install


